<?php
/** @var PowerstepScripts $block */

use Clerk\Clerk\Block\PowerstepScripts;

if ($block->shouldShow()):
    ?>
    <script>
        require(['jquery', 'mage/url'], function ($, urlBuilder) {
            function getPowerstepPopup(isAjax) {
                $("#clerk_powerstep").remove();
                $("#clerk_powerstep .clerk-slider").remove();
                const data = isAjax ? {isAjax: true} : {};
                $.ajax({
                    url: urlBuilder.build('clerk/powerstep/popup'),
                    data: data,
                    type: 'get',
                    success: function (res) {
                        if (res.length > 0) {
                            $('body').append(res);
                            Clerk('ui', 'popup', '.clerk-popup', 'show');
                            Clerk("content", ".clerk_powerstep_templates > span");

                        }
                    }
                });
            }

            $(document).on('ajax:addToCart', function (e) {
                getPowerstepPopup(true);
            });

            $(document).ready(function () {
                if (document.querySelector('[data-ui-id="message-success"]')) {
                    getPowerstepPopup();
                }
            });

        });
    </script>
<?php endif; ?>